# SPDX-License-Identifier: Apache-2.0
"""Tests for the ASF half of tools/generate_board_ve.py.

The electrical attributes (pull-up / pull-down / drive strength) are CPLD
configuration on this part: there is no runtime register for them, so they are
rendered into <board_dir>/board.generated.asf, which build_bitstream.sh folds
into logic/board.asf. What the tests pin down is the
rendering itself, the vendor's parameter rules, and the two ways a pin map can
ask for something that cannot be built.
"""

import importlib.util
import pathlib
import sys

TOOLS = pathlib.Path(__file__).resolve().parents[1]


def load(name):
    spec = importlib.util.spec_from_file_location(name, TOOLS / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


gen = load("generate_board_ve")


def render(**props):
    props.setdefault("mcu-pins", [])
    props.setdefault("cpld-pins", [])
    return gen.render_asf(props)


def test_no_electrical_attributes_renders_nothing():
    text, notes = render()
    assert text == ""
    assert notes == []


def test_pull_up_uses_the_vendor_spelling():
    text, notes = render(**{"agm,pull-ups": [96], "mcu-pins": [96]})
    assert notes == []
    assert ("set_instance_assignment -name WEAK_PULL_UP_RESISTOR "
            "-to PIN_96 ON") in text
    assert text.startswith("# Generated by tools/generate_board_ve.py")


def test_pull_down_is_the_cfg_keep_form():
    # The vendor note says pull-down exists only as CFG_KEEP 2'b01 -extension;
    # there is no WEAK_PULL_DOWN spelling to use here.
    text, _ = render(**{"agm,pull-downs": [2], "mcu-pins": [2]})
    assert ("set_instance_assignment -name CFG_KEEP -to PIN_2 2'b01 "
            "-extension") in text
    assert "WEAK_PULL_DOWN" not in text


def test_drive_strength_is_index_paired_and_2ma_steps():
    text, _ = render(**{"agm,drive-strength-pins": [96, 97],
                        "agm,drive-strength-ma": [16, 4],
                        "mcu-pins": [96, 97]})
    assert "-name CURRENT_STRENGTH -to PIN_96 16MA" in text
    assert "-name CURRENT_STRENGTH -to PIN_97 4MA" in text


def test_a_pin_cannot_be_pulled_both_ways():
    try:
        render(**{"agm,pull-ups": [96], "agm,pull-downs": [96],
                  "mcu-pins": [96]})
    except ValueError as exc:
        assert "PIN_96" in str(exc)
    else:
        raise AssertionError("a pin with both pulls must be refused")


def test_strength_outside_the_vendor_range_is_refused():
    for bad in (0, 1, 3, 34):
        try:
            render(**{"agm,drive-strength-pins": [96],
                      "agm,drive-strength-ma": [bad], "mcu-pins": [96]})
        except ValueError as exc:
            assert "PIN_96" in str(exc)
        else:
            raise AssertionError(f"{bad} mA must be refused")


def test_mismatched_strength_lists_are_refused():
    try:
        render(**{"agm,drive-strength-pins": [96, 97],
                  "agm,drive-strength-ma": [16], "mcu-pins": [96, 97]})
    except ValueError as exc:
        assert "drive-strength" in str(exc)
    else:
        raise AssertionError("unpaired strength lists must be refused")


def test_a_pull_on_an_unrouted_pin_is_reported_not_rendered():
    # A pull on a pin nothing drives is a note, not an error: the ASF line is
    # still emitted (the pin exists), but the pin map has nothing there.
    text, notes = render(**{"agm,pull-ups": [12], "mcu-pins": [96]})
    assert any("PIN_12" in n for n in notes)
    assert "PIN_12" in text
