#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
#
# check_pin_routing.sh — the pin-routing gate, in one command.
#
# Three things describe the same route:
#
#   1. tools/agm_af_pins.yaml          function -> AFSEL bank/bit (silicon)
#   2. dts/riscv/agm/pinctrl-*.dtsi    the committed agm,pins fragments
#   3. the bitstream's board.ve/.v     what the fabric actually wires
#
# A change to any of them can silently disagree with the others -- the pin
# list is a plain dts array, the fragments are committed build products and
# the bitstream is generated by a tool outside this repo. This script is the
# single entry point that runs every check that can be run without a board:
# a CI job (or a pre-push hook) only has to call it.
#
# Usage:
#   tools/check_pin_routing.sh                       # AF table + unit tests,
#                                                    # incl. the committed
#                                                    # fragments vs their pin
#                                                    # lists (no build needed)
#   tools/check_pin_routing.sh --dts <zephyr.dts>    # + fragment freshness
#   tools/check_pin_routing.sh --dts <zephyr.dts> \
#                              --netlist <board.vx>  # + function/pin vs fabric
#
# --dts must be the *merged* devicetree (${PROJECT_BINARY_DIR}/zephyr.dts),
# not zephyr.dts.pre. --netlist is the pre-route wrapper gen_vlog emits
# (logic/board.vx, or the vendor pair in tools/tests/fixtures/); board.ve is
# picked up from the sibling path unless --ve/--no-ve say otherwise.
#
# Exit codes: 0 ok, 1 a check failed, 2 usage.
#
# `../.gitea/workflows/pin-routing.yml` runs the no-argument form on every push;

set -eu

SELF_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO=$(dirname -- "$SELF_DIR")
PYTHON=${PYTHON:-${VIRTUAL_ENV:-}/bin/python3}
[ -x "$PYTHON" ] || PYTHON=python3

DTS_LIST=
NETLIST=
AF_ARGS=
VERBOSE=1

usage() {
	echo "usage: $0 [--dts <zephyr.dts>]... [--netlist <board.vx>]" >&2
	echo "          [--ve <board.ve>|--no-ve] [--af <agm_af_pins.yaml>] [--quiet]" >&2
	exit 2
}

VE_ARGS=
while [ $# -gt 0 ]; do
	case "$1" in
	--dts) [ $# -ge 2 ] || usage; DTS_LIST="$DTS_LIST $2"; shift 2 ;;
	--netlist) [ $# -ge 2 ] || usage; NETLIST=$2; shift 2 ;;
	--ve) [ $# -ge 2 ] || usage; VE_ARGS="--ve $2"; shift 2 ;;
	--no-ve) VE_ARGS="--no-ve"; shift ;;
	--af) [ $# -ge 2 ] || usage; AF_ARGS="--af $2"; shift 2 ;;
	--quiet) VERBOSE=0; shift ;;
	*) usage ;;
	esac
done

FAILED=0

step() {
	if [ "$VERBOSE" -eq 1 ]; then
		echo ">>> $*"
	fi
}

fail() {
	echo "FAIL: $*" >&2
	FAILED=1
}

# --- 1. the AF table against its sources of truth ----------------------
step "check_af_table.py (114 rows, vendor header when the SDK is present)"
"$PYTHON" "$SELF_DIR/check_af_table.py" $AF_ARGS || fail "check_af_table.py"

# --- 2. the tools' own regression tests --------------------------------
step "tools/tests (pure Python, no board needed)"
( cd "$REPO" && PYTHONPATH="$SELF_DIR" "$PYTHON" -m unittest discover -s tools/tests ) \
	|| fail "tools/tests"

# --- 3. the committed fragments, and the netlist when one is given -----
if [ -z "$DTS_LIST" ]; then
	echo "note: no --dts given, so the merged-devicetree half was skipped" >&2
	echo "      (tools/tests still re-derived the committed fragments from" >&2
	echo "      their pin lists). To check fragment freshness end to end, pass" >&2
	echo "      the merged devicetree west build leaves behind:" >&2
	echo "        $0 --dts <build-dir>/zephyr/zephyr.dts" >&2
	echo "      and, to check the fabric too, --netlist <board.vx> (or" >&2
	echo "      tools/tests/fixtures/example_board.v). Not zephyr.dts.pre." >&2
	if [ -n "$NETLIST" ]; then
		fail "--netlist needs a --dts to compare it against"
	fi
fi

for dts in $DTS_LIST; do
	if [ ! -f "$dts" ]; then
		fail "$dts: not a file"
		continue
	fi
	step "generate_pinctrl_dtsi.py --check $dts"
	"$PYTHON" "$SELF_DIR/generate_pinctrl_dtsi.py" --dts "$dts" --check $AF_ARGS \
		|| fail "generate_pinctrl_dtsi.py --check $dts"
	if [ -n "$NETLIST" ]; then
		step "check_pinctrl.py --dts $dts --netlist $NETLIST"
		"$PYTHON" "$SELF_DIR/check_pinctrl.py" --dts "$dts" \
			--netlist "$NETLIST" $VE_ARGS $AF_ARGS \
			|| fail "check_pinctrl.py --netlist $NETLIST"
	fi
done

if [ "$FAILED" -ne 0 ]; then
	echo "pin-routing check FAILED (see above)" >&2
	exit 1
fi
echo "pin-routing check OK"
